#Create lib_simpleloader.so from loader.c
so: loader.c loader.h
	gcc -fPIC -m32 -shared -o lib_simpleloader.so loader.c
	
#Provide the command for cleanup
# clean:
# already covered in the main Makefile.

